package config

const JavaTemplateInitPath string = "javaTemplate/init"
const JavaTemplateCodePath string = "javaTemplate/init/java"
const JavaTemplateResourcePath string = "javaTemplate/init/resources"
const MybatisPath string = "mybatis"
const JavaUtilPath string = "utils"
const JavaConfigPath string = "config"
const DefaultGroupName string = "com.github"
const DefaultArtifactName string = "learn"
const JavaPath = "src/main/java"
const JavaResourcePath = "src/main/resources"
const DtoName = "DTO"
const RequestDtoName = "InputDTO"
const JavaControllerFileName = "Controller.java"
const JavaServiceFileName = "Service.java"
const JavaServiceImplFileName = "ServiceImpl.java"
const JavaStubFileName = "Stub.java"
const GitIgnoreFileName = ".gitignore"
const DotProjectFileName = ".project"
const ReadmeFileName = "README.md"
const PomXmlFileName = "pom.xml"
const JavaApplicationFileName = "Application.java"