spring:
  {{ if .SupportI18n }}
  messages:
    basename: i18n/messages
    encoding: UTF-8
  {{ end }}
  profiles: dev
  security:
    enabled: true
  datasource:
    druid:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:{{.Database.Type}}://{{.Database.Host}}/{{.Database.DatabaseName}}
      username: {{.Database.Username}}
      password: {{.Database.Password}}
      driverClassName: {{.JdbcDriverClass}}
      # open /druid/index.html
      # dataSource Pool configuration
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      exceptionSorter: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙（防止SQL注入）
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      # # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true