package config

// Default Config
const DefaultGroupName string = "com.github"
const DefaultBaseURLName string = "api/v1"
const DefaultArtifactName string = "learn"
const DefaultHttpMethod string = "POST"
// Template Config
const JavaTemplateInitPath string = "javaTemplate/init"
const JavaTemplateInitCodePath string = "javaTemplate/init/java"
const JavaTemplateResourcePath string = "javaTemplate/init/resources"
const JavaTemplateCodePath string = "javaTemplate/code"
// Default
const MybatisPath string = "mybatis"
const JavaUtilPath string = "utils"
const JavaConfigPath string = "config"
const JavaCommonPath string = "common"
const JavaControllerPath string = "controller"
const JavaServicePath string = "service"
const JavaServiceImplPath string = "service/impl"

const JavaPath = "src/main/java"
const JavaResourcePath = "src/main/resources"
//***************************************DTO***************************
const RowLimiter = "\n"
const ImportPrefix = "import "
const JavaSuffixName = ".java"
const JavaDtoPath string = "dto"
const JavaDtoRequestPath string = "dto/request"
const ImportDtoRequestPath string = "dto.request"
const JavaDtoResponsePath string = "dto/response"
const ImportDtoResponsePath string = "dto.response"
const ImportRequestDto = "InputDTO"
const ImportResponseDto = "OutputDTO"
const SpringMapping = "Mapping"
const ImportSpringAnnotation = "import org.springframework.web.bind.annotation."
//***************************************DTO***************************
const JavaControllerFileName = "Controller.java"
const JavaServiceFileName = "Service.java"
const JavaServiceImplFileName = "ServiceImpl.java"
const JavaMethodControllerFileName = "method/ControllerMethod.java"
const JavaMethodServiceFileName = "method/ServiceMethod.java"
const JavaMethodServiceImplFileName = "method/ServiceImplMethod.java"
const JavaStubFileName = "Stub.java"
const GitIgnoreFileName = ".gitignore"
const DotProjectFileName = ".project"
const ReadmeFileName = "README.md"
const PomXmlFileName = "pom.xml"
const JavaApplicationFileName = "Application.java"